---
title: "Learn R now!!! (infomercial)"
author: "Julia Piaskowski"
date: "2023-03-07" 
format: 
  revealjs:
    theme: white
editor: source
---

## ASM 240 Computer Applications in Biophysical Systems 

*(3 credits)*

This course is designed as an introductory course to computer applications with specific emphasis on applications used in agriculture and life sciences. Content includes spreadsheet management, database management, data analysis, data visualization, and presentation applications. Recommended preparation: three credits of college math. Two lectures and one 2-hour lab per week.

---

{infomercial image}

---

## What is R? 

> R is a free software environment for statistical computing and graphics. 
> *--[R Core Team](https://www.r-project.org/)*

> R is a programming language for statistical computing and graphics....
> *--[Wikipedia](https://en.wikipedia.org/wiki/R_(programming_language))* 

[Invented in the 1970s at Bell Labs](https://sas.uwaterloo.ca/~rwoldfor/software/R-code/historyOfS.pdf)

---

::: {.center}
## What Can R do? 

- set of 'base' functions
- [20,000+ contributed packages](https://cran.r-project.org/web/packages/)
::: 

---

## Data Analysis

- math calculations
- [statistical analysis](https://cran.r-project.org/web/views/)
- [deep learning](https://tensorflow.rstudio.com/)
- [natural language models](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html)
- [GIS and spatial applications](https://cran.r-project.org/web/views/Spatial.html)

R has a solution for everything. 

---

## Data Preparation

suite of package: the [tidyverse]()

{vegetable pics}]

---

## Static Data Visualization

[some lovely examples](https://www.cedricscherer.com/top/dataviz/)

---

## dynamic data visualization

{steph curry image}

[gganimate](https://gganimate.com/)


## interactive data visualizations

::: {.center}

{plotly example of soil texture map - https://plotly.com/r/ternary-contour/}

:::

---

## web apps

[Shiny apps](https://shiny.rstudio.com/)
[Idaho variety testing]()

## write & publish reports

- Includes narratives: introduction, discussion, conclusion, etc
- use R code to run analysis and output results and/or illustrative plots
- embed mathematical equations, images, tables of results, diagrams

---

## build & publish tutorials online

[spatial statistics book](https://idahoagstats.github.io/guide-to-field-trial-spatial-analysis/)

---

## build websites

- [example 1](agstats.io), [example 2](https://idahoagstats.github.io/r-for-ag-scientists/)
- so many options: [quarto](https://quarto.org/docs/websites/), [blogdown + hugo](https://bookdown.org/yihui/blogdown/)

---

## R in Agriculture

- widely used in agronomy, crop science, and soil science
- precision ag: uses some R and python
- animal science: SAS
- agricultural econ: python, point-and-click software
- weed science, plant pathology, entomology: R & SAS
- [agricultural packages in R](https://shiny.rstudio.com/)

---

## How to learn R

- invest time + effort
- many free resources out there:
  - [my curriculum!](https://idahoagstats.github.io/r-for-ag-scientists/)
  - [other options](https://agstats.io/post/learning-r/)

---

##

{image: operators are standing by!}



